compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/plugin-prepare.cjs
    spec: "@vlight/plugin-prepare"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
